alpha_vantage: # Done
    api_key: "2MVB897KC89W77PT" # Free tier available, but key required.

quandl: # Done
    api_key: "9ZgDHLXxzcdz5kNh1ZJf" # Nasdaq Data Link, free datasets available, but key often needed for API access.

wrds: #TODO: Complete Registration
    credentials: "YOUR_WRDS_INSTITUTIONAL_CREDENTIALS" # Institutional access, typically username/password or IP-based. Not a traditional API key.

fred: # Done
    api_key: "af5f7262ae44f2a5fb03bd07ac9e56c1" # Federal Reserve Economic Data, key required for API access.

edgar_api: #TODO: Complete Registration
    api_key: "YOUR_EDGAR_API_KEY" # EDGAR API, often requires registration or rate limits.

tiingo: #TODO: Complete Registration
    api_key: "YOUR_TIINGO_API_KEY" # Limited free tier, key required.

polygon_io: #TODO: Complete Registration
    api_key: "YOUR_POLYGON_IO_API_KEY" # Limited free tier, key required.

twitter_api: #TODO: Complete Registration
    api_key: "YOUR_TWITTER_API_KEY" # Free tier available, but key required for access.

news_api: #TODO: Complete Registration
    api_key: "YOUR_NEWS_API_KEY" # e.g., GNews, NewsAPI - free tier available, but key required.

oecd: #TODO: Complete Registration
    api_key: "YOUR_OECD_API_KEY" # Some datasets free, API key might be needed for programmatic access.

world_bank_api: #TODO: Complete Registration
    api_key: "YOUR_WORLD_BANK_API_KEY" # Some datasets free, API key might be needed for programmatic access.

imf_data: #TODO: Complete Registration
    api_key: "YOUR_IMF_API_KEY" # Some datasets free, API key might be needed for programmatic access.

similarweb: #TODO: Complete Registration
    api_key: "YOUR_SIMILARWEB_API_KEY" # Limited free tier, key might be required for API access.

ibkr_api: #TODO: Complete Registration
    api_key: "YOUR_IBKR_API_KEY" # Interactive Brokers API, typically requires an account and specific setup.