# backtest_configs.yaml

# Parameters for backtesting (e.g., dates, rebalancing frequency, slippage)

backtest_defaults:
  start_date: "2015-01-01"
  end_date: "2023-12-31"
  initial_capital: 1000000 # $1 Million
  rebalance_frequency: "monthly" # or "weekly", "quarterly", "daily"
  commission_rate: 0.0005 # 0.05% per trade
  slippage_bps: 1 # 1 basis point (0.01%)
  benchmark_symbol: "^GSPC" # S&P 500

# Rolling window validation settings
rolling_window:
  window_size_years: 3 # Size of the training window in years
  step_size_months: 6 # How often to re-train and re-evaluate in months

# Stress testing regimes
market_regimes:
  - name: "bull_market"
    start: "2017-01-01"
    end: "2019-12-31"
  - name: "bear_market_2020"
    start: "2020-02-01"
    end: "2020-04-30"
  - name: "high_volatility_2022"
    start: "2022-01-01"
    end: "2022-12-31"

# Sensitivity analysis parameters
sensitivity_params:
  signal_thresholds: [0.01, 0.02, 0.03] # Example: different thresholds for signal strength
  rebalance_frequencies: ["monthly", "quarterly"] # Example: different rebalance frequencies